service: mykick-api
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  stage: dev
  apiGateway:
    shouldStartNameWithService: true

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-doppler
  - serverless-offline

custom:
  webpack:
    packager: 'yarn'
    includeModules:
      forceInclude:
        - '@nestjs/platform-express'
        - 'mysql2'
        - 'swagger-ui-express'
  serverless-offline:
    noPrependStageInUrl: true

functions:
  app:
    handler: src/main.handler
    events:
      - http:
          method: ANY
          path: '{proxy+}'
  extend:
    handler: src/schedulers/extend.handler
    events:
      - schedule: 'cron(0 1 ? * 2-6 *)'
